# Generated by Django 5.2.1 on 2025-05-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVeterinaria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacuna',
            old_name='fecha',
            new_name='fecha_aplicacion',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='nombre_vacuna',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
